// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_vpc_pair

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VpcPairResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"deploy": schema.BoolAttribute{
				Required:            true,
				Description:         "Deploy vPC pair",
				MarkdownDescription: "Deploy vPC pair",
			},
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the fabric to add switches to",
				MarkdownDescription: "Name of the fabric to add switches to",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The Terraform Unique Identifier for the vPC pair resource",
				MarkdownDescription: "The Terraform Unique Identifier for the vPC pair resource",
			},
			"peer_switch_id": schema.StringAttribute{
				Required:            true,
				Description:         "Serial number of the peer switch in the vPC pair.",
				MarkdownDescription: "Serial number of the peer switch in the vPC pair.",
			},
			"switch_id": schema.StringAttribute{
				Required:            true,
				Description:         "Serial number of the switch where the vPC pair is being configured.",
				MarkdownDescription: "Serial number of the switch where the vPC pair is being configured.",
			},
			"use_virtual_peerlink": schema.BoolAttribute{
				Required:            true,
				Description:         "Set to true to use virtual peer link",
				MarkdownDescription: "Set to true to use virtual peer link",
			},
		},
		Description:         "Resource to configure vPC pair on a switch. Note only VXLAN EVPN fabric is supported",
		MarkdownDescription: "Resource to configure vPC pair on a switch. Note only VXLAN EVPN fabric is supported",
	}
}

type VpcPairModel struct {
	Deploy             types.Bool   `tfsdk:"deploy"`
	FabricName         types.String `tfsdk:"fabric_name"`
	Id                 types.String `tfsdk:"id"`
	PeerSwitchId       types.String `tfsdk:"peer_switch_id"`
	SwitchId           types.String `tfsdk:"switch_id"`
	UseVirtualPeerlink types.Bool   `tfsdk:"use_virtual_peerlink"`
}
